### ISSUE TITLE
can't find PARTUUID

### ISSUE THREAD

**Issue by ghost** [sigboe/GPD-Arch-LUKS-LVM#15]
Hello there, I followed your guide but after rebooting the system I get the following error message:

```
ERROR: device 'PARTUUID=xxxxxxxxxxxx` not found. Skipping fsck.
mount: /new_root: can't find PARTUUID=xxxxxxxxx.
You are now being dropped into an emergency shell.
sh: can't access tty; job control turned off
[rootfs ]#
```

How can I solve this?

**Comment by sigboe** [comment]
I dont know why **You** got this error and I need to pay attention to see if other people get it as well, then potentially change the guide.

But lets fix your install without reinstalling first. Maybe we get some clues.

First off we need to boot in using chroot. Luckily I made a page on the wiki explaining that. (since I had to do it several times while debugging the install guide my self, and instructed others)

https://github.com/sigboe/GPD-ArchISO/wiki/Troubleshooting-encrypted-install-using-live-USB

Then I suggest dumping the whole contents of `blkid` to the end of your boot entry

    blkid >> /boot/loader/entries/arch.conf

Then we edit the boot entry.

    nano /boot/loader/entries/arch.conf

Now I'd like a screenshot of your how this file looks (sure use your phone to do that or something), thats your boot entry + the output on blkid tacked on.

Just guessing here you are trying to do a dual boot? In that case I was always planning to make the guide compatible with that but never got around to it. The gist of what you need to do is get the UUID of the drive (the one you did luksformat on) between `cryptdevice=UUID=` and `:luks`

**Comment by Stedelie** [comment]
Hello Again!

I'm following your guide but I use the non-encrypted disk installation, I don't really know what my luks partition is.

One other thing, if I try to execute `swapon` I get:
`sh: swapon: not found`

**Comment by ghost** [comment]
Hello again!

I'm not sure about this command:
`cryptsetup luksOpen /dev/mmcblk0p2 luks`

I didn't encrypt my disk and I'm not sure where is my luks partition. By the way I'm not dual booting, just Arch-linux :)

**Comment by sigboe** [comment]
That guide is meant to chroot encrypted installs 😃 

Its much simpler chrooting into unencrypted installs

Just mount the disks as you did when you installed them

    mount /dev/<partition name like mmcblk0p3 or something> /mnt

and do the same for /mnt/boot and /mnt/home

Then

    arch-chroot /mnt /usr/bin/zsh  

Then read the https://github.com/sigboe/GPD-ArchISO/wiki/Unencrypted-installation#configuring-boot-environment to see what might be wrong. Post back here too.

**Comment by ghost** [comment]
Alright, my bad! Basically, the problem was that this command:
`blkid | grep mmcblk0p3 | cut -f10 -d\" > /boot/loader/entries/arch.conf`

was redirecting an empty output, so I run this command:
`blkid | grep mmcblk0p3 " > /boot/loader/entries/arch.conf`

and I cut the part that I didn't need with vim. Unfortunately, I left the UUID code instead of the PARTUUID. Now is booting!
